#!/bin/bash 

#we need disk usage use%
#which directories are using high diskusage we need to filter 

DISK_USAGE=$(df -hT | grep -v Use)
THRESHOLD=1
IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)


while IFS= read -r line 
do 
  USAGE=$( echo "$line" | awk '{print $6}' | cut -d '%' -f1 )
  PARTITION=$(echo "$line" | awk '{print $7}' )
  if [ $USAGE -ge $THRESHOLD ]
  then 
      MSG+="high disk usage found in : $USAGE : $PARTITION \n"
  fi    

done <<< $DISK_USAGE

echo " server details : $IP : $MSG "